// First Grade Mandarin — 2026/27 assessment schedule
// Characters use TRADITIONAL forms (Broadway Elementary / Gao Laoshi & Liu Laoshi).
// Source: "2026 1. HFW School Locations" newsletter — test Wednesday 9/16/26.
// Each newsletter has two parts, so each test gets two entries below:
//   - "hfw"        → recognition only (listen / read / speak)
//   - "characters" → dictation portion (students must be able to WRITE these)
// `image` is the illustration shown with the word so the kid can build an association.
// Files live in img/ and are generated by scripts/make_icons.py (flat SVG, same style as the bunny).

const WEEKS = [
  {
    id: "hfw-1",
    track: "hfw",
    label: "HFW · School Locations (recognize)",
    dateRange: "9/8/26 – 9/16/26",
    words: [
      { hanzi: "教室",   pinyin: "jiào shì",     english: "classroom",              image: "img/classroom.svg" },
      { hanzi: "圖書館", pinyin: "tú shū guǎn",  english: "library",                image: "img/library.svg" },
      { hanzi: "操場",   pinyin: "cāo chǎng",    english: "playground / field",     image: "img/playground.svg" },
      { hanzi: "禮堂",   pinyin: "lǐ táng",      english: "auditorium",             image: "img/auditorium.svg" },
      { hanzi: "餐廳",   pinyin: "cān tīng",     english: "restaurant / cafeteria", image: "img/restaurant.svg" },
      { hanzi: "食堂",   pinyin: "shí táng",     english: "cafeteria / dining hall", image: "img/cafeteria.svg" },
      { hanzi: "洗手間", pinyin: "xǐ shǒu jiān", english: "restroom",               image: "img/restroom.svg" },
      { hanzi: "辦公室", pinyin: "bàn gōng shì", english: "office",                 image: "img/office.svg" },
      { hanzi: "東",     pinyin: "dōng",         english: "east",                   image: "img/east.svg" },
      { hanzi: "南",     pinyin: "nán",          english: "south",                  image: "img/south.svg" },
      { hanzi: "西",     pinyin: "xī",           english: "west",                   image: "img/west.svg" },
      { hanzi: "北",     pinyin: "běi",          english: "north",                  image: "img/north.svg" },
    ],
  },
  {
    id: "chars-1",
    track: "characters",
    label: "Characters · Dictation (write)",
    dateRange: "9/8/26 – 9/16/26",
    words: [
      { hanzi: "是",   pinyin: "shì",     english: "is / am / are",   image: "img/yes.svg" },
      { hanzi: "個",   pinyin: "gè",      english: "(measure word)",  image: "img/one.svg" },
      { hanzi: "去",   pinyin: "qù",      english: "go",              image: "img/go.svg" },
      { hanzi: "有",   pinyin: "yǒu",     english: "have / there is", image: "img/have.svg" },
      { hanzi: "東",   pinyin: "dōng",    english: "east",            image: "img/east.svg" },
      { hanzi: "西",   pinyin: "xī",      english: "west",            image: "img/west.svg" },
      { hanzi: "東西", pinyin: "dōng xī", english: "stuff / things",  image: "img/things.svg" },
    ],
  },
];
