// Kindergarten Mandarin — 2025/26 assessment schedule
// Characters use TRADITIONAL forms (Broadway Elementary / Chen Laoshi).
// HFW category word lists are sensible kindergarten defaults — review with teacher.

const WEEKS = [
  {
    id: "chars-1",
    track: "characters",
    label: "Characters · Feb 9",
    dateRange: "2/9/26 – 2/13/26",
    words: [
      { hanzi: "大", pinyin: "dà",   english: "big" },
      { hanzi: "小", pinyin: "xiǎo", english: "small" },
      { hanzi: "日", pinyin: "rì",   english: "sun / day" },
      { hanzi: "月", pinyin: "yuè",  english: "moon / month" },
      { hanzi: "上", pinyin: "shàng", english: "up / above" },
      { hanzi: "下", pinyin: "xià",  english: "down / below" },
      { hanzi: "左", pinyin: "zuǒ",  english: "left" },
      { hanzi: "右", pinyin: "yòu",  english: "right" },
    ],
  },
  {
    id: "chars-2",
    track: "characters",
    label: "Characters · Feb 23",
    dateRange: "2/23/26 – 2/27/26",
    words: [
      { hanzi: "中", pinyin: "zhōng", english: "middle" },
      { hanzi: "水", pinyin: "shuǐ",  english: "water" },
      { hanzi: "天", pinyin: "tiān",  english: "sky / day" },
      { hanzi: "人", pinyin: "rén",   english: "person" },
      { hanzi: "木", pinyin: "mù",    english: "wood / tree" },
      { hanzi: "口", pinyin: "kǒu",   english: "mouth" },
      { hanzi: "山", pinyin: "shān",  english: "mountain" },
      { hanzi: "土", pinyin: "tǔ",    english: "dirt / earth" },
    ],
  },
  {
    id: "chars-3",
    track: "characters",
    label: "Characters · Mar 9",
    dateRange: "3/9/26 – 3/13/26",
    words: [
      { hanzi: "女", pinyin: "nǚ",   english: "girl / female" },
      { hanzi: "好", pinyin: "hǎo",  english: "good" },
      { hanzi: "火", pinyin: "huǒ",  english: "fire" },
      { hanzi: "石", pinyin: "shí",  english: "stone" },
      { hanzi: "的", pinyin: "de",   english: "(possessive)" },
      { hanzi: "是", pinyin: "shì",  english: "is / to be" },
      { hanzi: "田", pinyin: "tián", english: "field" },
      { hanzi: "力", pinyin: "lì",   english: "strength" },
    ],
  },
  {
    id: "chars-4",
    track: "characters",
    label: "Characters · Mar 23",
    dateRange: "3/23/26 – 3/26/26",
    words: [
      { hanzi: "耳", pinyin: "ěr",  english: "ear" },
      { hanzi: "門", pinyin: "mén", english: "door" },
      { hanzi: "心", pinyin: "xīn", english: "heart" },
      { hanzi: "子", pinyin: "zǐ",  english: "child" },
      { hanzi: "可", pinyin: "kě",  english: "can / may" },
      { hanzi: "以", pinyin: "yǐ",  english: "with / by" },
      { hanzi: "白", pinyin: "bái", english: "white" },
      { hanzi: "不", pinyin: "bù",  english: "not / no" },
    ],
  },
  {
    id: "chars-5",
    track: "characters",
    label: "Characters · Apr 13",
    dateRange: "4/13/26 – 4/17/26",
    words: [
      { hanzi: "我", pinyin: "wǒ",   english: "I / me" },
      { hanzi: "你", pinyin: "nǐ",   english: "you" },
      { hanzi: "牛", pinyin: "niú",  english: "cow" },
      { hanzi: "羊", pinyin: "yáng", english: "sheep" },
      { hanzi: "兔", pinyin: "tù",   english: "rabbit" },
      { hanzi: "狗", pinyin: "gǒu",  english: "dog" },
      { hanzi: "吃", pinyin: "chī",  english: "eat" },
    ],
  },
  {
    id: "chars-6",
    track: "characters",
    label: "Characters · Apr 27",
    dateRange: "4/27/26 – 5/1/26",
    words: [
      { hanzi: "去", pinyin: "qù",   english: "go" },
      { hanzi: "要", pinyin: "yào",  english: "want" },
      { hanzi: "有", pinyin: "yǒu",  english: "have" },
      { hanzi: "看", pinyin: "kàn",  english: "look / see" },
      { hanzi: "玩", pinyin: "wán",  english: "play" },
      { hanzi: "會", pinyin: "huì",  english: "can / will" },
      { hanzi: "年", pinyin: "nián", english: "year" },
    ],
  },
  {
    id: "chars-7",
    track: "characters",
    label: "Characters · May 11",
    dateRange: "5/11/26 – 5/15/26",
    words: [
      { hanzi: "文",   pinyin: "wén",       english: "language / writing" },
      { hanzi: "早",   pinyin: "zǎo",       english: "morning / early" },
      { hanzi: "這是", pinyin: "zhè shì",   english: "this is" },
      { hanzi: "今天", pinyin: "jīn tiān",  english: "today" },
      { hanzi: "明天", pinyin: "míng tiān", english: "tomorrow" },
      { hanzi: "朋友", pinyin: "péng yǒu",  english: "friend" },
    ],
  },

  // -------- High Frequency Words (exact lists from HFW PDF) --------
  // bonus:true matches the ** words in the PDF
  {
    id: "hfw-1",
    track: "hfw",
    label: "HFW · Numbers, Dates, Colors",
    dateRange: "2/17/26 – 2/20/26",
    words: [
      { hanzi: "一", pinyin: "yī",   english: "one" },
      { hanzi: "二", pinyin: "èr",   english: "two" },
      { hanzi: "三", pinyin: "sān",  english: "three" },
      { hanzi: "四", pinyin: "sì",   english: "four" },
      { hanzi: "五", pinyin: "wǔ",   english: "five" },
      { hanzi: "六", pinyin: "liù",  english: "six" },
      { hanzi: "七", pinyin: "qī",   english: "seven" },
      { hanzi: "八", pinyin: "bā",   english: "eight" },
      { hanzi: "九", pinyin: "jiǔ",  english: "nine" },
      { hanzi: "十", pinyin: "shí",  english: "ten" },
      { hanzi: "百", pinyin: "bǎi",  english: "hundred", bonus: true },
      { hanzi: "零", pinyin: "líng", english: "zero",    bonus: true },
      { hanzi: "今天是", pinyin: "jīn tiān shì",  english: "today is" },
      { hanzi: "明天是", pinyin: "míng tiān shì", english: "tomorrow is" },
      { hanzi: "昨天是", pinyin: "zuó tiān shì",  english: "yesterday was", bonus: true },
      { hanzi: "星期",   pinyin: "xīng qí",       english: "week" },
      { hanzi: "一週",   pinyin: "yī zhōu",       english: "one week" },
      { hanzi: "紅色", pinyin: "hóng sè",  english: "red" },
      { hanzi: "黃色", pinyin: "huáng sè", english: "yellow", bonus: true },
      { hanzi: "藍色", pinyin: "lán sè",   english: "blue",   bonus: true },
      { hanzi: "綠色", pinyin: "lǜ sè",    english: "green",  bonus: true },
      { hanzi: "白色", pinyin: "bái sè",   english: "white" },
      { hanzi: "黑色", pinyin: "hēi sè",   english: "black" },
    ],
  },
  {
    id: "hfw-2",
    track: "hfw",
    label: "HFW · Family & Places",
    dateRange: "3/2/26 – 3/6/26",
    words: [
      { hanzi: "爸爸", pinyin: "bà ba",    english: "father" },
      { hanzi: "媽媽", pinyin: "mā ma",    english: "mother" },
      { hanzi: "姊姊", pinyin: "jiě jie",  english: "older sister" },
      { hanzi: "妹妹", pinyin: "mèi mei",  english: "younger sister" },
      { hanzi: "哥哥", pinyin: "gē ge",    english: "older brother" },
      { hanzi: "弟弟", pinyin: "dì di",    english: "younger brother" },
      { hanzi: "家人", pinyin: "jiā rén",  english: "family", bonus: true },
      { hanzi: "公園",     pinyin: "gōng yuán",     english: "park",          bonus: true },
      { hanzi: "家",       pinyin: "jiā",           english: "home" },
      { hanzi: "學校",     pinyin: "xué xiào",      english: "school",        bonus: true },
      { hanzi: "朋友的家", pinyin: "péng yǒu de jiā", english: "friend's home" },
      { hanzi: "超市",     pinyin: "chāo shì",      english: "supermarket",   bonus: true },
    ],
  },
  {
    id: "hfw-3",
    track: "hfw",
    label: "HFW · Pronouns, Animals, Pointing",
    dateRange: "3/16/26 – 3/20/26",
    words: [
      { hanzi: "你",   pinyin: "nǐ",    english: "you" },
      { hanzi: "我",   pinyin: "wǒ",    english: "I" },
      { hanzi: "他",   pinyin: "tā",    english: "he" },
      { hanzi: "她",   pinyin: "tā",    english: "she" },
      { hanzi: "我們", pinyin: "wǒ men", english: "we", bonus: true },
      { hanzi: "狗", pinyin: "gǒu",  english: "dog" },
      { hanzi: "貓", pinyin: "māo",  english: "cat",    bonus: true },
      { hanzi: "牛", pinyin: "niú",  english: "cow" },
      { hanzi: "兔", pinyin: "tù",   english: "rabbit" },
      { hanzi: "馬", pinyin: "mǎ",   english: "horse",  bonus: true },
      { hanzi: "羊", pinyin: "yáng", english: "sheep" },
      { hanzi: "魚", pinyin: "yú",   english: "fish",   bonus: true },
      { hanzi: "那是", pinyin: "nà shì",  english: "that is", bonus: true },
      { hanzi: "這是", pinyin: "zhè shì", english: "this is" },
    ],
  },
  {
    id: "hfw-4",
    track: "hfw",
    label: "HFW · School & Weather",
    dateRange: "4/6/26 – 4/10/26",
    words: [
      { hanzi: "日期",   pinyin: "rì qī",     english: "date" },
      { hanzi: "名字",   pinyin: "míng zì",   english: "name" },
      { hanzi: "校長",   pinyin: "xiào zhǎng", english: "principal", bonus: true },
      { hanzi: "老師",   pinyin: "lǎo shī",   english: "teacher" },
      { hanzi: "年",     pinyin: "nián",      english: "year" },
      { hanzi: "中文",   pinyin: "zhōng wén", english: "Chinese" },
      { hanzi: "英文",   pinyin: "yīng wén",  english: "English" },
      { hanzi: "數學",   pinyin: "shù xué",   english: "math",  bonus: true },
      { hanzi: "課",     pinyin: "kè",        english: "class", bonus: true },
      { hanzi: "晴天",   pinyin: "qíng tiān", english: "sunny", bonus: true },
      { hanzi: "下雨",   pinyin: "xià yǔ",    english: "raining" },
      { hanzi: "陰天",   pinyin: "yīn tiān",  english: "cloudy", bonus: true },
      { hanzi: "太陽",   pinyin: "tài yáng",  english: "sun",    bonus: true },
      { hanzi: "月亮",   pinyin: "yuè liang", english: "moon" },
      { hanzi: "星星",   pinyin: "xīng xīng", english: "star" },
    ],
  },
  {
    id: "hfw-5",
    track: "hfw",
    label: "HFW · Opposites",
    dateRange: "4/20/26 – 4/23/26",
    words: [
      { hanzi: "大小",        pinyin: "dà / xiǎo",       english: "big / small" },
      { hanzi: "上下",        pinyin: "shàng / xià",     english: "up / down" },
      { hanzi: "左右",        pinyin: "zuǒ / yòu",       english: "left / right" },
      { hanzi: "前後",        pinyin: "qián / hòu",      english: "front / back",       bonus: true },
      { hanzi: "高低",        pinyin: "gāo / dī",        english: "high / low",         bonus: true },
      { hanzi: "熱冷",        pinyin: "rè / lěng",       english: "hot / cold",         bonus: true },
      { hanzi: "長短",        pinyin: "cháng / duǎn",    english: "long / short",       bonus: true },
      { hanzi: "裡外",        pinyin: "lǐ / wài",        english: "inside / outside",   bonus: true },
      { hanzi: "多少",        pinyin: "duō / shǎo",      english: "more / less" },
      { hanzi: "可以／不可以", pinyin: "kě yǐ / bù kě yǐ", english: "can / can't" },
      { hanzi: "是／不是",     pinyin: "shì / bù shì",    english: "yes / no" },
    ],
  },
  {
    id: "hfw-6",
    track: "hfw",
    label: "HFW · Verbs, Feelings, Classroom",
    dateRange: "5/4/26 – 5/8/26",
    words: [
      { hanzi: "說", pinyin: "shuō", english: "speak" },
      { hanzi: "看", pinyin: "kàn",  english: "look" },
      { hanzi: "寫", pinyin: "xiě",  english: "write", bonus: true },
      { hanzi: "畫", pinyin: "huà",  english: "draw",  bonus: true },
      { hanzi: "玩", pinyin: "wán",  english: "play" },
      { hanzi: "去", pinyin: "qù",   english: "go" },
      { hanzi: "有", pinyin: "yǒu",  english: "have" },
      { hanzi: "開心", pinyin: "kāi xīn",  english: "happy" },
      { hanzi: "喜歡", pinyin: "xǐ huan",  english: "like", bonus: true },
      { hanzi: "愛",   pinyin: "ài",       english: "love", bonus: true },
      { hanzi: "會",   pinyin: "huì",      english: "can",  bonus: true },
      { hanzi: "男生", pinyin: "nán shēng", english: "boy" },
      { hanzi: "女生", pinyin: "nǚ shēng",  english: "girl" },
      { hanzi: "學生", pinyin: "xué shēng", english: "student",    bonus: true },
      { hanzi: "書包", pinyin: "shū bāo",   english: "school bag", bonus: true },
      { hanzi: "加",   pinyin: "jiā",       english: "plus",       bonus: true },
    ],
  },
  {
    id: "hfw-7",
    track: "hfw",
    label: "HFW · Senses, Body, Greeting",
    dateRange: "5/18/26 – 5/22/26",
    words: [
      { hanzi: "吃", pinyin: "chī",  english: "eat" },
      { hanzi: "聽", pinyin: "tīng", english: "hear",  bonus: true },
      { hanzi: "聞", pinyin: "wén",  english: "smell", bonus: true },
      { hanzi: "看", pinyin: "kàn",  english: "look" },
      { hanzi: "摸", pinyin: "mō",   english: "touch", bonus: true },
      { hanzi: "耳朵", pinyin: "ěr duo",  english: "ear" },
      { hanzi: "鼻子", pinyin: "bí zi",   english: "nose", bonus: true },
      { hanzi: "眼睛", pinyin: "yǎn jīng", english: "eye", bonus: true },
      { hanzi: "頭",   pinyin: "tóu",     english: "head", bonus: true },
      { hanzi: "你好", pinyin: "nǐ hǎo",   english: "hello" },
      { hanzi: "再見", pinyin: "zài jiàn", english: "bye",  bonus: true },
    ],
  },
];
